numbers = [21, 20, 2, 1, 11, 21]
print(numbers.index(21))
print(23 in numbers)
print(numbers.count(21))
numbers.append(22)
print(numbers)
numbers.insert(2,45)
print(numbers)
numbers.pop()
print(numbers)
numbers.sort()
print(numbers)
numbers.reverse()
print(numbers)
